<?php

namespace Tests\Unit\ORM\Entities;

use App\ORM\Entities\OrderProduct;
use Tests\TestCase;

class OrderProductTest extends TestCase
{
    /** @var \App\ORM\Entities\OrderProduct */
    protected $orderProduct;
    
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }
    
    /**
     * @covers \App\ORM\Entities\OrderProduct::__construct
     * @covers \App\ORM\Entities\Order::setData
     * @covers \App\ORM\Entities\OrderProduct::setId
     * @covers \App\ORM\Entities\OrderProduct::setPrice
     * @covers \App\ORM\Entities\OrderProduct::setType
     * @covers \App\ORM\Entities\OrderProduct::setUpc
     * @covers \App\ORM\Entities\OrderProduct::setSku
     * @covers \App\ORM\Entities\OrderProduct::setName
     * @covers \App\ORM\Entities\OrderProduct::setProductId
     * @covers \App\ORM\Entities\OrderProduct::setOrderId
     * @covers \App\ORM\Entities\OrderProduct::getId
     * @covers \App\ORM\Entities\OrderProduct::getPrice
     * @covers \App\ORM\Entities\OrderProduct::getType
     * @covers \App\ORM\Entities\OrderProduct::getUpc
     * @covers \App\ORM\Entities\OrderProduct::getSku
     * @covers \App\ORM\Entities\OrderProduct::getName
     * @covers \App\ORM\Entities\OrderProduct::getProductId
     * @covers \App\ORM\Entities\OrderProduct::getOrderId
     */
    public function testConstruction()
    {
        $data               = [
            'order_id'   => 100,
            'product_id' => 1000,
            'name'       => 'Product Name',
            'sku'        => '',
            'upc'        => '',
            'type'       => 'physical',
            'base_price' => 10,
            'id'         => 1,
        ];
        $this->orderProduct = new OrderProduct([]);
        $this->orderProduct->setData($data);
        $this->assertEquals($data['order_id'], $this->orderProduct->getOrderId());
        $this->assertEquals($data['product_id'], $this->orderProduct->getProductId());
        $this->assertEquals($data['name'], $this->orderProduct->getName());
        $this->assertEquals($data['sku'], $this->orderProduct->getSku());
        $this->assertEquals($data['upc'], $this->orderProduct->getUpc());
        $this->assertEquals($data['type'], $this->orderProduct->getType());
        $this->assertEquals($data['base_price'], $this->orderProduct->getPrice());
        $this->assertEquals($data['id'], $this->orderProduct->getId());
    }
    
    /**
     * @covers \App\ORM\Entities\OrderProduct::setId
     * @covers \App\ORM\Entities\OrderProduct::setPrice
     * @covers \App\ORM\Entities\OrderProduct::setType
     * @covers \App\ORM\Entities\OrderProduct::setUpc
     * @covers \App\ORM\Entities\OrderProduct::setSku
     * @covers \App\ORM\Entities\OrderProduct::setName
     * @covers \App\ORM\Entities\OrderProduct::setProductId
     * @covers \App\ORM\Entities\OrderProduct::setOrderId
     * @covers \App\ORM\Entities\OrderProduct::getId
     * @covers \App\ORM\Entities\OrderProduct::getPrice
     * @covers \App\ORM\Entities\OrderProduct::getType
     * @covers \App\ORM\Entities\OrderProduct::getUpc
     * @covers \App\ORM\Entities\OrderProduct::getSku
     * @covers \App\ORM\Entities\OrderProduct::getName
     * @covers \App\ORM\Entities\OrderProduct::getProductId
     * @covers \App\ORM\Entities\OrderProduct::getOrderId
     */
    public function testSettersAndGetters()
    {
        $this->orderProduct = new OrderProduct([]);
        $data               = [
            'order_id'   => 100,
            'product_id' => 1000,
            'name'       => 'Product Name',
            'sku'        => '',
            'upc'        => '',
            'type'       => 'physical',
            'base_price' => 10,
            'id'         => 1,
        ];
        
        $this->orderProduct
            ->setOrderId($data['order_id'])
            ->setProductId($data['product_id'])
            ->setName($data['name'])
            ->setSku($data['sku'])
            ->setUpc($data['upc'])
            ->setType($data['type'])
            ->setPrice($data['base_price'])
            ->setId($data['id']);
        $this->assertEquals($data['order_id'], $this->orderProduct->getOrderId());
        $this->assertEquals($data['product_id'], $this->orderProduct->getProductId());
        $this->assertEquals($data['name'], $this->orderProduct->getName());
        $this->assertEquals($data['sku'], $this->orderProduct->getSku());
        $this->assertEquals($data['upc'], $this->orderProduct->getUpc());
        $this->assertEquals($data['type'], $this->orderProduct->getType());
        $this->assertEquals($data['base_price'], $this->orderProduct->getPrice());
        $this->assertEquals($data['id'], $this->orderProduct->getId());
    }
}